### ISSUE TITLE
Does this support patch 1.01?

### ISSUE THREAD

**Issue by wefalltomorrow** [TFP-dev/JuicedWidescreenFix#2]
Would be great to know, cheers.

**Comment by TFP-dev** [comment]
Currently it's working only with 1.0. Next version will be compatible with 1.01.

**Comment by wefalltomorrow** [comment]
Good to know, is there an ETA on the next update?

**Comment by TFP-dev** [comment]
I will update this today.

**Comment by wefalltomorrow** [comment]
Awesome, thank you!

**Comment by wefalltomorrow** [comment]
> 
> 
> I will update this today.

Awesome, thank you!

**Comment by wefalltomorrow** [comment]
> 
> 
> I will update this today.

Any luck making any progress?

**Comment by TFP-dev** [comment]
Update released. Closing issue.
